### ISSUE TITLE
RISC-V instruction implementation

### ISSUE THREAD

**Issue by cadebrown** [ChemicalDevelopment/CARVE#10]
We need the RISC-V instructions implemented as a VM in 'src/exec.c'

- [x] RV32I
- [ ] M
- [ ] A
- [ ] F
- [ ] D

**Comment by RahilV2000** [comment]
> We need the RISC-V instructions implemented as a VM in 'src/exec.c'
> 
> - [x] RV32I
> - [ ] M
> - [ ] A
> - [ ] F
> - [ ] D

RV32I
